### ISSUE TITLE
My remote server is not responding.

### ISSUE THREAD

**Issue by gfhd0054** [kaist-cp/cs420#66] opened 2020-04-18 13:28 UTC
Hello. This is Jaejun Lee, a student of cs420 2020.
Somehow, I couldn't access to my linus server. I haven't changed anything about my configuration...
This is the error message. Please help me...
![notConnectedErrorMsg1](https://user-images.githubusercontent.com/52437623/79639011-cd3aa580-81c3-11ea-85ba-679d525dfa28.JPG)
![notConnectedErrorMsg2](https://user-images.githubusercontent.com/52437623/79639015-d3c91d00-81c3-11ea-9c88-e074d72377b9.JPG)

Additionally, I''m trying to do assignment in my local window server.
However, when I command `cargo run -- -p examples/fibonacci.c`, it prints out the file doesn't exist.
This is the error message.
![fileNotExistErrorMsg](https://user-images.githubusercontent.com/52437623/79639028-df1c4880-81c3-11ea-85de-e8542734bdb7.JPG)

I have debugged when this error occurs, and it seems 26th line in parse.rs gives this message.
I post screenshots of where the problem occurs.

<bin/kecc.rs>
![notConnectedErrorMsg2](https://user-images.githubusercontent.com/52437623/79639031-e0e60c00-81c3-11ea-9231-7a784b126283.JPG)

<src/parse.rs>
![fileNotExistErrorMsg3](https://user-images.githubusercontent.com/52437623/79639037-ed6a6480-81c3-11ea-9b63-0652ff86d9b3.JPG)

Really thanks in advance.

**Comment by jeehoonkang** [comment] 2020-04-18 15:37
- Please paste code as text, not image.
- The cs420 server is up and running.  Would you please retry?
- We don't support Windows for the time being.  But just in case, did you merge the upstream changes to your local development?

**Comment by gfhd0054** [comment] 2020-04-18 15:45
- New kinds of error message has emerged.

`00:41:09.034] > 25900ef9d7af: running`
`> 
[00:41:09.080] > Acquiring lock on /home/s20170490/.vscode-server/bin/ff915844119ce9485abfe8aa907`
`> 6ec76b5300ddd/vscode-remote-lock.s20170490.ff915844119ce9485abfe8aa9076ec76b5300`
`> ddd`
`> \ln /home/s20170490/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/`
`> vscode-remote-lock.s20170490.ff915844119ce9485abfe8aa9076ec76b5300ddd.target /ho`
`> me/s20170490/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/vscode-`
`> remote-lock.s20170490.ff915844119ce9485abfe8aa9076ec76b5300ddd`
`> Installation already in progress...`
`> 25900ef9d7af##24##`
`> ln: failed to create hard link '/home/s20170490/.vscode-server/bin/ff915844119ce`
`> 9485abfe8aa9076ec76b5300ddd/vscode-remote-lock.s20170490.ff915844119ce9485abfe8a`
`> a9076ec76b5300ddd': File exists`

- Yes, I have merged the most recent one.

Thanks for your response even after the midnight...!

**Comment by jeehoonkang** [comment] 2020-04-18 15:55
- Please use: https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#fenced-code-blocks
- The error message means you need to wait for software to be installed, probably for a few minutes.
- Maybe try `examples\fibonacci.c`, not `examples/fibonacci.c`?

**Comment by gfhd0054** [comment] 2020-04-18 16:10
- Now the new error message has disappeared but it is still being disconnected. Should I create another public ssh key...?

 - I tried using \ for Windows already but it didn't work.

```
C:\Users\gfhd0\Desktop\카이스트\2020 봄학기\컴파일러설계(CS420)\Project\kecc-public>cargo run -- -p examples\fibonacci.c
    Finished dev [unoptimized + debuginfo] target(s) in 0.28s
     Running `target\debug\kecc.exe -p examples\fibonacci.c`
ParseError(PreprocessorError(Os { code: 2, kind: NotFound, message: "지정된 파일을 찾을 수 없습니다." }))
error: process didn't exit successfully: `target\debug\kecc.exe -p examples\fibonacci.c` (exit code: 1)
```

**Comment by jeehoonkang** [comment] 2020-04-18 16:26
- I think it's too difficult to debug your local environment in this board.  Let's try to connect to the server.  Also, please create separate issues for separate questions (connection & local environment).

- Messages like `Acquiring lock on /home/s20170490/.vscode-server/bin/ff915844119ce9485abfe8aa907` means you succeeded in connecting to the server.  The problem is not connection, but something else.  Please describe your error message more precisely.

**Comment by gfhd0054** [comment] 2020-04-18 16:45
Thanks for your deep comment. I would use this issue for my connection problem.
My error messages are following.
```
[01:37:48.302] Log Level: 2
[01:37:48.308] remote-ssh@0.51.0
[01:37:48.308] win32 x64
[01:37:48.311] SSH Resolver called for "ssh-remote+cs420", attempt 1
[01:37:48.312] SSH Resolver called for host: cs420
[01:37:48.312] Setting up SSH remote "cs420"
[01:37:48.486] Using commit id "ff915844119ce9485abfe8aa9076ec76b5300ddd" and quality "stable" for server
[01:37:48.489] Install and start server if needed
[01:37:48.500] Checking ssh with "ssh -V"
[01:37:48.666] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[01:37:48.669] Running script with connection command: ssh -T -D 59835 cs420 bash
[01:37:48.674] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[01:37:48.935] > 
```
And with some blank lines....
```
> ]0;C:\WINDOWS\System32\cmd.exe
[01:37:48.935] Got some output, clearing connection timeout
[01:37:48.950] >
```
Also with some blank lines...
```
[01:38:10.034] > ssh: connect to host cp-service.kaist.ac.kr port 10005: Connection timed out
> 
[01:38:10.042] > 프로세스에서 없는 파이프에 쓰려고 했습니다.
> 
[01:38:10.379] "install" terminal command done
[01:38:10.381] Install terminal quit with output: 프로세스에서 없는 파이프에 쓰려고 했습니다.
[01:38:10.381] Received install output: 프로세스에서 없는 파이프에 쓰려고 했습니다.
[01:38:10.384] Stopped parsing output early. Remaining text: 프로세스에서 없는 파이프에 쓰려고 했습니다.
[01:38:10.385] Failed to parse remote port from server output
[01:38:10.387] Resolver error: 
[01:38:10.425] ------
``` 

I am studying about ssh connection from the bottom. Would you give me some insights or suggestions..?

**Comment by cmpark0126** [comment] 2020-04-20 06:43
@gfhd0054 sorry for late comments, If you still have problems connecting to SSH, please contact me: chunmyong.park@kaist.ac.kr.

**Comment by Conatee** [comment] 2020-04-23 10:05
@cmpark0126 I'm having the same problem in this issue. Can I get the solution to the problem if it is resolved?

**Comment by cmpark0126** [comment] 2020-04-24 04:30
@gfhd0054 Is it resolved?

**Comment by gfhd0054** [comment] 2020-04-25 15:43
@cmpark0126 It's not yet resolved but I'm currently doing my assignment on the vmWare Ubuntu, and the all cargo instructions seem to work fine.

**Comment by cmpark0126** [comment] 2020-04-30 01:15
@gfhd0054 Hmm I've had this problem before. If you can connect the server with terminal or putty, please delete `/home/s20170490/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/vscode-remote-lock.s20170490.ff915844119ce9485abfe8aa9076ec76b5300ddd`. Then reconnect to the server via VSCode.

**Comment by cmpark0126** [comment] 2020-04-30 14:54
@gfhd0054 Please check this issue and solution: https://github.com/kaist-cp/cs420/issues/91. Maybe it's the same problem as well. ;)

**Comment by jeehoonkang** [comment] 2020-05-02 07:54
#91 seems to be the solution to most connection problems.  Closing, but feel free to reopen it if you still experience connection problems. @gfhd0054

**Closed by jeehoonkang** 2020-05-02 07:54 UTC
