### ISSUE TITLE
[HW2] Build fail due to my particular implementation of HW1

### ISSUE THREAD

**Issue by lomotos10** [kaist-cp/cs420#70] opened 2020-04-20 08:15 UTC
When I compiled HW2 before doing any work for test purposes, Rust resulted in build error.
The reason was as follows:

In default code of `src/ir/write_ir.rs:46`, the code calls `init.write_string()`, where init is `lang_c::ast::Initializer`.
However, my implementation of HW1 used only `write_line()` method for every data type.

In this case, what file should I modify: the `write_ir.rs` file; or the `write_c.rs` file, to fix the build error? Also, in the case I should fix `write_c.rs`, should I submit this modified file to HW1 submit site again?

**Comment by cmpark0126** [comment] 2020-04-20 08:47
Thank you for the question and sorry for the confusion caused by the latest update.

As I mentioned at https://github.com/kaist-cp/cs420/issues/8#issuecomment-616396938, now you need to consider [`lang_c::ast::Initializer::List`](https://docs.rs/lang-c/0.8.1/lang_c/ast/enum.Initializer.html#variant.List). So, please modify `write_c.rs` to support this element.

Again, sorry for the confusion caused by the latest update.

**Comment by cmpark0126** [comment] 2020-04-20 08:50
FYI, we have a plan to ask you again to resubmit your homework. So, please wait next announcement.

**Comment by cmpark0126** [comment] 2020-04-24 04:32
Closing. Feel free to reopen it if you have further questions :)

**Closed by cmpark0126** 2020-04-24 04:32 UTC
